<template>
    <div class="currency-exchanger">
        <div class="holder">
            <div
                v-if="screenType === 'currency-converter'">
                <h2 class="sub-title sub-title-xs font-bold ">Enter a value for EUR</h2>
                <form>
                    <InputElement
                        label="Euros"
                        inputId="base-currency"
                        inputName="base-currency"
                        inputType="number"
                        placeholder="Please enter an ammout"
                        :hideLabel="true"
                        :triggerValidation="triggerValidation"
                        @emittedErrorInput="handleErrorInput"
                        @emittedValidInput="handleValidInput" />
                </form>
                <h2 class="sub-title sub-title-xs font-bold ">Select two...</h2>
                <DescriptionList
                    :list="exchangedRates"
                    @emitDesActiveListElem="generateComparableCurrencies" />
                <button
                    class="cta"
                    type="button"
                    @click="handleClickCompareCta">
                    Compare
                </button>
            </div>
            <div
                class="currency-exchanger_hystory"
                v-else-if="screenType === 'currency-compare'">
                <div class="currency-exchanger_hystory-title align-horizontal-center">
                    <h2 class="sub-title sub-title-sm font-bold ">{{getBaseCurrencyValue}} EUR</h2>
                    <p class="text text-sm">(ammount entered at step 1)</p>
                </div>
                <button
                    class="cta"
                    type="button"
                    @click="handleClickResetCta">
                    Reset form
                </button>
            </div>
        </div>
    </div>
</template>

<script>
import '../scss/components/currency-exchanger.scss'

import { mapActions, mapGetters } from 'vuex'
import axios from 'axios'
import { evaluate } from 'mathjs'
import flushPromises from 'flush-promises'
import numeral from 'numeral'
import moment from 'moment'
import timeOperations from '../helpers/timeOperation'

import InputElement from './InputElement.vue'
import DescriptionList from './DescriptionList.vue'


export default {
    name: 'CurrencyExchanger',
    data (){
        return {
            otherBaseCurrencies: {},   // holds the initial exchange rates for 1 EUR
            formErrorState: [],        // holds the errors generated by the form
            exchangedRates: [],        // holds the converted currency based on the base currency
            compareCurrencies: [],     // the currencies selected by the user in the description list
            triggerValidation: 0,      // triggers form validation
            screenType: 'currency-converter'
        }
    },
    components: {
        InputElement,
        DescriptionList
    },
    computed: {
        ...mapGetters('currencyExchanger', ['getBaseCurrencyValue'])
    },
    watch: {
        // triggers the currency converter when the base currency is bigger than 0
        getBaseCurrencyValue (){
           this.generateExchangeRates()
        },
        compareCurrencies (){
            if(this.compareCurrencies.length > 1){
                if(this.getBaseCurrencyValue){
                    // if the base currency has valid user input and the user selected two comparable currencies, change the screen
                    this.toggleScreens('currency-compare')

                    this.requestHistoricalRates()
                }else{
                    // if the base currency doesn't have valid user input and the user selected two comparable currencies trigger the validation
                    this.triggerFormValidation()
                }
            }
        }
    },
    methods: {
        // store action
        ...mapActions('currencyExchanger', ['setBaseCurrencyValue']),
        toggleScreens (screenType){
            this.screenType = screenType
        },
        triggerFormValidation (){
            this.triggerValidation += 1
        },
        // convert the base currency in other currencies
        generateExchangeRates (){
            this.exchangedRates = []

            for(let currency in this.otherBaseCurrencies) {
                let currencyObj = {
                    value: evaluate(`${this.otherBaseCurrencies[currency]} * ${this.getBaseCurrencyValue}`),
                    currency: currency
                }

                // keep demcimals equal to two
                currencyObj.value = currencyObj.value > 0 ? numeral(currencyObj.value).format('0[.]00') : currencyObj.value


                this.exchangedRates.push(currencyObj)
            }
        },
        // store the active currencies from the description list
        generateComparableCurrencies (activeList){
            this.compareCurrencies = []

            activeList.forEach(el => {
                this.compareCurrencies.push(this.exchangedRates[el].currency)
            })
        },
        async handleClickCompareCta (){
            // reset form errors array
            this.formErrorState = []

            // revalidate
            this.triggerFormValidation()

            await flushPromises();

            // if form passes validation
            if(this.formErrorState.length === 0) this.requestHistoricalRates()
        },
        requestHistoricalRates (){
            const pastDates = timeOperations.methods.generateLasNumberOfDays(5),
                currencies = this.compareCurrencies.join(',')

            let titleArray = [],
                currenciesValuesArray = []

            if(currencies && pastDates.length){
                for(let i = 0; i < pastDates.length; i += 1){
                    axios.get(`http://localhost:3000/api/history?currencies=${currencies}&date=${pastDates[i]}`)
                    .then(response => {
                        this.toggleScreens('currency-compare')
                        console.log(response)
                    })
                    .catch(error => {
                      console.log(error)
                    })
                }
            }
        },
        handleClickResetCta (){
            // reset the form
            this.setBaseCurrencyValue(0)

            this.toggleScreens('currency-converter')
        },
        handleErrorInput (obj){
            // store the value
            this.formErrorState.push(obj)

            if(obj.name === 'base-currency'){
                // reset store value if input with the name base-currency emits a invalid value
                this.setBaseCurrencyValue(0)
            }
        },
        handleValidInput (obj){
            // if the input with the name base-currency emits a valid value update the store
            if(obj.name === 'base-currency') this.setBaseCurrencyValue(obj.value)
        },
        getOtherCurencies (){
            this.otherBaseCurrencies = {'USD':1.121805,'GBP':0.909191,'AUD':1.63457,'CAD':1.536688,'CHF':1.063339,'CNY':7.940589,'SEK':10.471658,'NZD':1.745864}

            this.generateExchangeRates()

            // axios.get('http://localhost:3000/api/latest')
            // .then(response => {
            //   this.otherBaseCurrencies = response.data.data.rates
            // })
            // .catch(error => {
            //   console.log(error);
            // })
        }
    },
    mounted (){
        // fetch the currencies from the API
        this.getOtherCurencies()
    }
}
</script>